### ISSUE TITLE
Question regarding ids sdk configuration

### ISSUE THREAD

**Issue by saqib-ahmed** [CiscoDevNet/uccx-sample-code#4]
I couldn't find any example of idsclientlib.conf file anywhere in the documentation. I conjured up the following config file and it works for the oauth redirect.
```
ids1_url=https://finesse-url:8553/
ids.client.redirect_base_uri=<my callback>
ids.client.id=<code>
```
The problem is with the ids1_url. When I try to get `accessToken` using `client.getAccessToken(code, redirectURI)`, it tries to hit `https://url:8553/oauth/access_token` which returns 404. I tried various base URLs for ids1_url but nothing seems to work so far. 

@dekwan Can you please help with that? Let me know in case you need any further details.

**Comment by saqib-ahmed** [comment]
Found the solution. Used the answer from [here](https://stackoverflow.com/questions/51990207/how-do-you-authenticate-to-cisco-contact-center-express-identity-service) as a reference. My idsclientlib.conf file is as follows now:
```
ids1_url=https://finesse-url:8553/ids/v1/
ids.client.redirect_base_uri=<my callback>
ids.client.id=<code>
```

**Comment by saqib-ahmed** [comment]
@dekwan Can you please improve the documentation [here](https://developer.cisco.com/docs/contact-center-express/#!cisco-identity-service-client-sdk-guide/overview)? I had to reverse engineer the SDK a lot to make it work. It took me quite some time for a task that shouldn't have taken more than a couple of hours. 
I would love to contribute if this documentation is open-sourced. Let me know if that's the case.

**Comment by dekwan** [comment]
Hi.  The doc is not open sourced and the UCCX team is the owner of that doc. I'm sure they'd love to get feedback or your contributions. If you pass me the feedback, I can pass it on to them.

**Comment by dekwan** [comment]
I realized after the comment in your pull request that I do have permissions to edit the doc. If you would like to contribute, please pass me the information. I will verify it with the UCCX team and then make the update.

**Comment by saqib-ahmed** [comment]
Sure. I'll jot down some hurdles I've had along the way. Thanks for your prompt responses.
